# Generated by Django 4.1.9 on 2023-07-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Swasthya_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgency', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
