# Generated by Django 4.1.9 on 2023-07-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Swasthya_App', '0002_ambulance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('hospital', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
