# Generated by Django 4.1.9 on 2023-07-26 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Swasthya_App', '0003_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='added_date',
            field=models.CharField(default=datetime.datetime(2023, 7, 27, 1, 52, 19, 329522), max_length=100),
        ),
    ]
