# Generated by Django 4.1.9 on 2023-07-26 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Swasthya_App', '0004_doctor_added_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('problem', models.CharField(max_length=100)),
                ('booked_date', models.CharField(default=datetime.datetime(2023, 7, 27, 2, 7, 13, 565262), max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='added_date',
            field=models.CharField(default=datetime.datetime(2023, 7, 27, 2, 7, 13, 565262), max_length=100),
        ),
    ]
